# Generated by Django 5.1.2 on 2024-11-08 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('codigo', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=10)),
                ('correoPersonal', models.CharField(max_length=100, unique=True)),
                ('correoInstitucional', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('grupoSanguineo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('horaInicio', models.CharField(max_length=7)),
                ('horaFin', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divisist.persona')),
                ('estadoAcademico', models.CharField(max_length=20)),
                ('numeroMatricula', models.CharField(max_length=20)),
                ('fechaInscripcion', models.DateField()),
            ],
            bases=('divisist.persona',),
        ),
        migrations.AddField(
            model_name='departamento',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.facultad'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('creditos', models.IntegerField()),
                ('hasEquivalency', models.BooleanField(default=False)),
                ('cupos', models.IntegerField()),
                ('equivalencia', models.ManyToManyField(to='divisist.materia')),
                ('horario', models.ManyToManyField(to='divisist.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras_de_pensum', to='divisist.carrera')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='pensum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensums_de_carrera', to='divisist.pensum'),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('materias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='divisist.materia')),
            ],
        ),
        migrations.AddField(
            model_name='pensum',
            name='semestres',
            field=models.ManyToManyField(to='divisist.semestre'),
        ),
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divisist.semestre'),
        ),
        migrations.CreateModel(
            name='UsuarioCarnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='divisist.carrera')),
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='divisist.persona')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_carnet_documento', to='divisist.persona')),
                ('grupoSanguineo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_carnet_grupo', to='divisist.persona')),
                ('nombreCompleto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_carnet_nombre', to='divisist.persona')),
            ],
        ),
        migrations.CreateModel(
            name='NotaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodoAcademico', models.CharField(max_length=100)),
                ('primerPrevio', models.FloatField()),
                ('segundoPrevio', models.FloatField()),
                ('tercerPrevio', models.FloatField()),
                ('examenFinal', models.FloatField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.materia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodoAcademico', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.materia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodoAcademico', models.CharField(max_length=100)),
                ('materias', models.ManyToManyField(to='divisist.materia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.materia')),
                ('estudiantes', models.ManyToManyField(to='divisist.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divisist.persona')),
                ('tipoVinculacion', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.departamento')),
            ],
            bases=('divisist.persona',),
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.profesor'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajes', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.materia')),
                ('participantes', models.ManyToManyField(to='divisist.estudiante')),
                ('moderador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisist.profesor')),
            ],
        ),
    ]
