# Generated by Django 5.1.2 on 2024-11-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocarnet',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='usuariocarnet',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='usuariocarnet',
            name='grupoSanguineo',
        ),
        migrations.RemoveField(
            model_name='usuariocarnet',
            name='nombreCarrera',
        ),
        migrations.RemoveField(
            model_name='usuariocarnet',
            name='nombreCompleto',
        ),
    ]
